#!/usr/bin/env python3

from jotdown.parser import parse

import argparse
import os

own_directory = os.path.dirname(os.path.abspath(__file__))

argparser = argparse.ArgumentParser()
argparser.add_argument('input')
argparser.add_argument('-o', '--output', default='out.html')
argparser.add_argument('-s', '--style', default=os.path.join(own_directory, 'styles/solarized.css'))
argparser.add_argument('-c', '--citations', action='store_true')
argparser.add_argument('--debug', action='store_true')
args = argparser.parse_args()

if args.debug:
	fout_name = args.output + '.debug'
else:
	fout_name = args.output

with open(args.input, 'r') as f, open(fout_name, 'wb') as fout:

	# Use a built-in style file before attempting to load a custom one
	builtin_stylesheet = os.path.join(own_directory, 'styles', args.style + '.css')
	if os.path.isfile(builtin_stylesheet):
		stylesheet = builtin_stylesheet
	else:
		stylesheet = args.style

	doc = parse(f)
	doc.name = args.input.split('.')[0]  # Remove the extension for the title of the document

	if args.debug:
		fout.write(bytes(doc.emit_debug(level=0, ref_style=args.citations), 'utf-8'))
	else:
		fout.write(bytes(doc.emit_html(css=stylesheet, ref_style=args.citations), 'utf-8'))
